#!/usr/bin/perl
use warnings;
use strict;
my $x       = 50;
my $y       = 50;
my $density = 15;

print "$y.ox\n";
for (my $i = 0 ; $i < $y ; $i++) {
    for (my $j = 0 ; $j < $x ; $j++) {
        if (int(rand($y) * 2) < $density) {
            print "o";
        } else {
            print ".";
        }
    }
    print "\n";
}