# **************************************************************************** #
#                                                                              #
#                                                         ::::::::             #
#    Makefile                                           :+:    :+:             #
#                                                      +:+                     #
#    By: cuechtri <cuechtri@student.42.fr>            +#+                      #
#                                                    +#+                       #
#    Created: 2022/07/23 12:35:33 by ovan-rhe      #+#    #+#                  #
#    Updated: 2022/07/24 15:34:46 by cuechtri      ########   odam.nl          #
#                                                                              #
# **************************************************************************** #

NAME = rush-02

SRC = mainCOS.c string_functions.c create_output_string.c display_number.c dict_functions.c put_in_dict.c readInput.c split_number.c split_word.c dict_to_struct.c

FLAGS = -Wall -Werror -Wextra

compile:
	gcc $(FLAGS) -o $(NAME) $(SRC)

fclean:
	# some kind of clean function to get rid of the previous gcc
	
	/bin/rm -f $(NAME)
